{
	"feedNames": [
        "#a9a9a9",
        "#5f5f5f",
        "#484848",
        "#ffffff"
    ],
	"date": "#d5d5d5",
	"time": "#109291",
	"articleBorder": "#117efc",
	"previewBorder": "#117efc",
	"feedBorder": "#117efc",
    "feedBorderTitle": "#ffffff",
    "articleBorderTitle": "#ffffff",
    "previewBorderTitle": "#ffffff",
	"highlights": "#0c7a79",
	"tableHead": "#f0f0f0",
	"title": "#aeaeae",
	"unreadFeedName": "#FFFFFF",
	"totalColumn": "#3365a4",
	"unreadColumn": "#3365a4",
	"previewText": "#d0d0d1",
	"previewLink": "#39537e",
	"statusBackground": "#3365a4",
	"statusText": "#d0d0d1",
	"statusKey": "#FFFFFF",
	"statusBrackets": "#0f8697",
	"feedIcon": "🔖",
	"articleIcon": "🗞",
	"previewIcon": "📰",
	"linkMarker": "🌍",
	"unreadMarker": "🌟"
}

