{
	"feedNames": [
        "#b7da76",
        "#5b936a",
        "#7b543a",
        "#29495c"
    ],
	"date": "#b6c0cc",
	"time": "#9a93a0",
	"articleBorder": "#b7c0cf",
	"previewBorder": "#b7c0cf",
	"feedBorder": "#b7c0cf",
    "feedBorderTitle": "#b7c0cf",
    "articleBorderTitle": "#b7c0cf",
    "previewBorderTitle": "#b7c0cf",
	"highlights": "#efa14f",
	"tableHead": "#c086c9",
	"title": "#b7c0cf",
	"unreadFeedName": "#FFFFFF",
	"totalColumn": "#FFFFFF",
	"unreadColumn": "#FFFFFF",
	"previewText": "#FFFFFF",
	"previewLink": "#39537e",
	"statusBackground": "#8fbb71",
	"statusText": "#25282f",
	"statusKey": "#FFFFFF",
	"statusBrackets": "#c086c2",
	"feedIcon": "🔖",
	"articleIcon": "🗞",
	"previewIcon": "📰",
	"linkMarker": "🌍",
	"unreadMarker": "🌟"
}

